Modified marionette to work on hosted apps

diff --git a/bin/gaia-perf-marionette b/bin/gaia-perf-marionette
--- a/bin/gaia-perf-marionette
+++ b/bin/gaia-perf-marionette
@@ -72,7 +72,16 @@ esac
 echo '[' >&3
 SHARED_PERF=`find tests/performance -name "*_test.js" -type f`
 OLD_RESTART_B2G="$RESTART_B2G"
-for app in $APPS; do
+for appDir in $APPS; do
+  hasDir=`echo $appDir | grep -o ","`
+  if [ "$hasDir" == "," ]; then
+    dir=`echo $appDir | cut -d, -f1`
+    app=`echo $appDir | cut -d, -f2`
+  else
+    dir="apps"
+    app=$appDir
+  fi
+
   if [ -z "$FIRST_LOOP_ITERATION" ]; then
     FIRST_LOOP_ITERATION=done
   else
@@ -81,15 +90,16 @@ for app in $APPS; do
   if [[ "$app" == "system" ]] && [[ "$TEST_BOOT" -eq 2 ]] ; then
     # The system boot test manually manages the reboot/restart lifecycle
     # Using the TEST_BOOT=2 flag forces an opt-in to manually run this test
-    FILES_PERF=`test -d apps/$app/test/performance && find apps/$app/test/performance -name "*_test.js" -type f`
+    FILES_PERF=`test -d $dir/$app/test/performance && find $dir/$app/test/performance -name "*_test.js" -type f`
     export RESTART_B2G=0
   else
-    FILES_PERF=`test -d apps/$app/test/performance && find apps/$app/test/performance -name "*_test.js" \( ! -name "system_startup_test.js" \) -type f`
+    FILES_PERF=`test -d $dir/$app/test/performance && find $dir/$app/test/performance -name "*_test.js" \( ! -name "system_startup_test.js" \) -type f`
     export RESTART_B2G=$OLD_RESTART_B2G
   fi
   # wrap marionette-mocha with gaia's defaults. We also need to alter the paths to
   # xpcshell in available for email fake servers.
   export CURRENT_APP="$app"
+  export CURRENT_APP_DIR="$dir"
   OUT=`PATH=$XPCSHELL_DIR:$PATH $DIR/../node_modules/.bin/marionette-mocha \
     --timeout 60s \
     --profile-builder $SHARED/profile_builder.js \
@@ -101,8 +111,8 @@ for app in $APPS; do
     $@`
   # Bug 987383 if there is no output report an error.
   if [ -z "$OUT" ]; then
-    echo "$CURRENT_APP returned no output." >&2
-    echo "{ \"stats\": { \"suites\": 1, \"failures\": 1, \"error\": \"No output !\", \"application\": \""$CURRENT_APP"\" } }" >&3
+    echo "$CURRENT_APP_DIR/$CURRENT_APP returned no output." >&2
+    echo "{ \"stats\": { \"suites\": 1, \"failures\": 1, \"error\": \"No output !\", \"application\": \""$CURRENT_APP_DIR/$CURRENT_APP"\" } }" >&3
   else
     echo "$OUT" >&3
   fi
